"""Prepare a single Short's Remotion render data: copies its narration audio,
cold-open image, scene images, and a music bed into the Remotion project's
public/ dir, and writes a TS data file matching ShortComposition.tsx's
ShortData shape - real per-word timing throughout, no estimates, same
principle as prep_remotion_render.py for the main video.

Usage:
    python prep_short_render.py <short_id> <hook_overlay_text> <cta_text> \\
        <images_dir> <audio_dir> <coldopen_image_path> <remotion_dir> [--slug SLUG]
"""
import argparse
import json
import os
import shutil

FPS = 30
COLD_OPEN_SECONDS = 1.5
CTA_SECONDS = 3.5
WORDS_PER_CAPTION_CHUNK = 3

parser = argparse.ArgumentParser()
parser.add_argument("short_id")
parser.add_argument("hook_overlay_text")
parser.add_argument("cta_text")
parser.add_argument("images_dir")
parser.add_argument("audio_dir")
parser.add_argument("coldopen_image_path")
parser.add_argument("remotion_dir")
parser.add_argument("--slug", default=None)
args = parser.parse_args()

slug = args.slug or args.short_id
pub_subdir = f"shorts/{slug}"
PUB = os.path.join(args.remotion_dir, "public", pub_subdir)
os.makedirs(PUB, exist_ok=True)

timing_path = os.path.join(args.audio_dir, f"{args.short_id}_timing.json")
with open(timing_path, encoding="utf-8") as f:
    timing = json.load(f)

# narration audio
narration_src = os.path.join(args.audio_dir, f"{args.short_id}.mp3")
shutil.copyfile(narration_src, os.path.join(PUB, "narration.mp3"))

# cold-open image
shutil.copyfile(args.coldopen_image_path, os.path.join(PUB, "coldopen.png"))

# scene images
scene_entries = []
for s in timing["scenes"]:
    img_name = s["sceneId"] + ".png"
    src = os.path.join(args.images_dir, img_name)
    shutil.copyfile(src, os.path.join(PUB, img_name))
    scene_entries.append({
        "sceneId": s["sceneId"],
        "image": f"{pub_subdir}/{img_name}",
        "startFrame": round(s["startSeconds"] * FPS),
        "durationFrames": round(s["durationSeconds"] * FPS),
    })

# real per-word caption chunks (center-screen, grouped 3 words)
words = timing["captionWords"]
chunks = []
for i in range(0, len(words), WORDS_PER_CAPTION_CHUNK):
    group = words[i:i + WORDS_PER_CAPTION_CHUNK]
    chunks.append({
        "startFrame": round(group[0]["startSeconds"] * FPS),
        "endFrame": round(group[-1]["endSeconds"] * FPS),
        "words": [{"text": w["word"], "startFrame": round(w["startSeconds"] * FPS),
                   "endFrame": round(w["endSeconds"] * FPS)} for w in group],
    })

cold_open_frames = round(COLD_OPEN_SECONDS * FPS)
cta_frames = round(CTA_SECONDS * FPS)
narration_frames = round(timing["totalSeconds"] * FPS)
total_frames = cold_open_frames + narration_frames + cta_frames

# deterministic music-bed pick (same rule as royalty_free_music_tool's get_bed_track,
# offset by short_id so each short doesn't necessarily reuse the main video's track)
bed_n = (sum(ord(c) for c in slug) % 10) + 1
repo = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
bed_src = repo + f"/ProductionStudio/Assets/audio/music_bed/bed_{bed_n:02d}.mp3"
shutil.copyfile(bed_src, os.path.join(PUB, "bed.mp3"))

data = {
    "fps": FPS,
    "totalFrames": total_frames,
    "coldOpenFrames": cold_open_frames,
    "ctaFrames": cta_frames,
    "coldOpenImage": f"{pub_subdir}/coldopen.png",
    "hookOverlayText": args.hook_overlay_text,
    "ctaText": args.cta_text,
    "narrationAudio": f"{pub_subdir}/narration.mp3",
    "narrationStartFrame": cold_open_frames,
    "scenes": scene_entries,
    "captionChunks": chunks,
    "musicBed": f"{pub_subdir}/bed.mp3",
}

out_ts = os.path.join(args.remotion_dir, "src", f"{slug}_data.ts")
export_name = slug.upper()
with open(out_ts, "w", encoding="utf-8") as f:
    f.write("// GENERATED by prep_short_render.py - do not edit by hand\n")
    f.write(f"export const {export_name} = " + json.dumps(data, ensure_ascii=False, indent=2) + " as const;\n")

print(f"{slug}: total {total_frames} frames ({total_frames/FPS:.1f}s), "
      f"{len(scene_entries)} scenes, {len(chunks)} caption chunks, bed_{bed_n:02d}.mp3")
print("wrote", out_ts)
