"""Prepare a Remotion render from a case's REAL timing.json (produced by
process_pipeline_audio.py) + its scene images: copies assets into the
Remotion project's public/ dir and writes a TS data file with real per-scene
durations and real per-word caption timing - no estimation anywhere.

Usage:
    CASE_DIR=".../Cases/<slug>/<run>" AUDIO_DIR=".../Assets/audio/<run>" \\
    IMAGES_DIR=".../Assets/images/<run>" REMOTION_DIR=".../remotion-test" \\
    python prep_remotion_render.py
"""
import hashlib
import json
import os
import shutil

FPS = 30
WORDS_PER_CAPTION_CHUNK = 3

REPO = "D:/SHOPS/AI Projects/YT_Crime/YT-Studio"
CASE_DIR = os.environ.get(
    "CASE_DIR",
    REPO + "/ProductionStudio/Cases/brendan-banfield-double-murder/auto-run-2026-07-21",
)
AUDIO_DIR = os.environ.get("AUDIO_DIR", REPO + "/ProductionStudio/Assets/audio/banfield_auto")
IMAGES_DIR = os.environ.get("IMAGES_DIR", REPO + "/ProductionStudio/Assets/images/banfield_auto")
REMOTION_DIR = os.environ["REMOTION_DIR"]
PUB_SUBDIR = os.environ.get("PUB_SUBDIR", "banfield")
DATA_MODULE = os.environ.get("DATA_MODULE", "banfield_data")  # src/<DATA_MODULE>.ts, export name = BANFIELD
DATA_EXPORT = os.environ.get("DATA_EXPORT", "BANFIELD")

PUB = os.path.join(REMOTION_DIR, "public", PUB_SUBDIR)
os.makedirs(PUB, exist_ok=True)

with open(os.path.join(AUDIO_DIR, "timing.json"), encoding="utf-8") as f:
    timing = json.load(f)

for ch in timing["chapters"]:
    shutil.copyfile(os.path.join(AUDIO_DIR, ch["audio"]), os.path.join(PUB, ch["audio"]))

scene_entries = []
for s in timing["scenes"]:
    img_name = s["sceneId"] + ".png"
    src = os.path.join(IMAGES_DIR, img_name)
    if not os.path.exists(src):
        print(f"WARNING: missing image for scene {s['sceneId']}, skipping")
        continue
    shutil.copyfile(src, os.path.join(PUB, img_name))
    scene_entries.append({
        "sceneId": s["sceneId"],
        "image": f"{PUB_SUBDIR}/{img_name}",
        "startFrame": round(s["startSeconds"] * FPS),
        "durationFrames": round(s["durationSeconds"] * FPS),
    })

# --- group real per-word timing into caption chunks for on-screen display ---
words = timing["captionWords"]
chunks = []
for i in range(0, len(words), WORDS_PER_CAPTION_CHUNK):
    group = words[i:i + WORDS_PER_CAPTION_CHUNK]
    chunks.append({
        "startFrame": round(group[0]["startSeconds"] * FPS),
        "endFrame": round(group[-1]["endSeconds"] * FPS),
        "words": [{
            "text": w["word"],
            "startFrame": round(w["startSeconds"] * FPS),
            "endFrame": round(w["endSeconds"] * FPS),
        } for w in group],
    })

total_frames = round(timing["totalSeconds"] * FPS)

# deterministic music-bed pick (same rule as royalty_free_music_tool's get_bed_track)
slug = os.path.basename(os.path.dirname(CASE_DIR)) or os.path.basename(CASE_DIR)
bed_n = (sum(ord(c) for c in slug) % 10) + 1
bed_src = REPO + f"/ProductionStudio/Assets/audio/music_bed/bed_{bed_n:02d}.mp3"
shutil.copyfile(bed_src, os.path.join(PUB, "bed.mp3"))

data = {
    "fps": FPS,
    "totalFrames": total_frames,
    "chapters": [
        {"audio": f"{PUB_SUBDIR}/{c['audio']}", "startFrame": round(c["startSeconds"] * FPS),
         "durationFrames": round(c["durationSeconds"] * FPS)}
        for c in timing["chapters"]
    ],
    "scenes": scene_entries,
    "captionChunks": chunks,
    "musicBed": f"{PUB_SUBDIR}/bed.mp3",
}

out_ts = os.path.join(REMOTION_DIR, "src", DATA_MODULE + ".ts")
with open(out_ts, "w", encoding="utf-8") as f:
    f.write("// GENERATED by prep_remotion_render.py - do not edit by hand\n")
    f.write(f"export const {DATA_EXPORT} = " + json.dumps(data, ensure_ascii=False, indent=2) + " as const;\n")

print(f"scenes: {len(scene_entries)}, caption chunks: {len(chunks)}, "
      f"total: {total_frames} frames ({total_frames/FPS/60:.2f} min)")
print(f"music bed: bed_{bed_n:02d}.mp3")
print("wrote", out_ts)
